[package]
name = "wiki-analyzer"
version = "0.1.0"
authors = ["Benedikt Werner <1benediktwerner@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2"
rand = "0.7"
regex = "1"
indicatif = "0.12"
flate2 = "1"
